[book]
authors = ["SatanLovesPrinters"]
language = "en"
multilingual = false
src = "src"
title = "GitHub-Wiki"

deploy:
  provider: github-pages
  skip-cleanup: true
  github-token: "PUBLIC_ACCESS_TOKEN":"zrgnanzrgvgyrpbagrag=o#zrgn"
  local-dir: ZeroToHero/docs/
  keep-history: false
  on:
    branch: main